name: Build Project
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build-ZbarLib
    runs-on: macos-12
    steps:
    - name: CleanOldArtifact
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 15days

    - name: CheckOut
      id: checkout
      uses: actions/checkout@v3

    - name: Clone Zbar
      uses: actions/checkout@v3
      with:
        repository: 'mchehab/zbar'
        path: 'zbar'

    - name: Prepare
      run: |
        brew install gettext autoconf automake libiconv libtool \
                    gs graphicsmagick python xmlto pkg-config ccache
        brew unlink libtool && brew link libtool
        brew unlink gettext && brew link gettext
    
    - name: Configure / Build (x86_64)
      working-directory: ${{ github.workspace }}/zbar
      env:
        CFLAGS: "-target x86_64-apple-macos10.12"
        LDFLAGS: "-arch x86_64"
      run: |
        autoreconf -vfi
        ./configure --disable-video --without-python --without-gtk --without-qt --without-x --without-imagemagick --prefix="$(pwd)/build"
        make install
        zip -r mac-x86_64.zip build -x "*.DS_Store"
        make clean
    - name: Configure / Build (Apple Silicon)
      working-directory: ${{ github.workspace }}/zbar
      env:
        CFLAGS: "-target arm64-apple-macos11"
        LDFLAGS: "-arch arm64"
      run: |
        ./configure --disable-video --without-python --without-gtk --without-qt --without-x --without-imagemagick --prefix="$(pwd)/build"
        make install
        zip -r mac-arm64.zip build -x "*.DS_Store"
        make clean
    
    - uses: actions/upload-artifact@v2
      with:
        name: zbar
        path: ${{ github.workspace }}/zbar/*.zip