name: Build Project
on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.md'
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build-ZbarLib
    runs-on: macos-12
    steps:
    - name: CleanOldArtifact
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        expire-in: 15days

    - name: CheckOut
      id: checkout
      uses: actions/checkout@v3

    - name: Clone Zbar (with tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/checkout@v3
      with:
        repository: 'mchehab/zbar'
        tag: ${{github.ref_name}}
        path: 'zbar'
    
    - name: Clone Zbar (without tag)
      if: "!startsWith(github.ref, 'refs/tags/')"
      uses: actions/checkout@v3
      with:
        repository: 'mchehab/zbar'
        path: 'zbar'

    - name: Prepare
      run: |
        brew install libtool
        brew install gettext autoconf automake libiconv \
                    gs graphicsmagick python xmlto pkg-config ccache
        brew unlink libtool && brew link libtool
        brew unlink gettext && brew link gettext
    
    - name: Configure / Build (x86_64)
      working-directory: ${{ github.workspace }}/zbar
      env:
        CFLAGS: "-target x86_64-apple-macos10.12"
        LDFLAGS: "-arch x86_64"
      run: |
        autoreconf -vfi
        ./configure --disable-video --without-python --without-gtk --without-qt --without-x --without-imagemagick --prefix="$(pwd)/build-x86" --enable-shared --enable-static --without-xshm
        make install
        zip -r mac-x86_64.zip build-x86 -x "*.DS_Store"
        make clean
    - name: Configure / Build (Apple Silicon)
      working-directory: ${{ github.workspace }}/zbar
      run: |
        ./configure --disable-video --without-python --without-gtk --without-qt --without-x --without-imagemagick --prefix="$(pwd)/build-arm" --enable-shared --enable-static --without-xshm --host=arm64-apple-darwin
        make install
        zip -r mac-arm64.zip build-arm -x "*.DS_Store"
        make clean
    - name: Create Universal Binary
      working-directory: ${{ github.workspace }}/zbar
      run: |
        mkdir build-univeral
        mkdir build-univeral/lib
        lipo -create -arch arm64 ${{ github.workspace }}/zbar/build-arm/lib/libzbar.dylib -arch x86_64 ${{ github.workspace }}/zbar/build-arm/lib/libzbar.dylib -output build-univeral/lib/libzbar.dylib
        lipo -create -arch arm64 ${{ github.workspace }}/zbar/build-arm/lib/libzbar.a -arch x86_64 ${{ github.workspace }}/zbar/build-arm/lib/libzbar.a -output build-univeral/lib/libzbar.a
        cp -r ${{ github.workspace }}/zbar/build-arm/include ${{ github.workspace }}/zbar/build-univeral/include
        zip -r mac-univeral.zip build-univeral -x "*.DS_Store"
    - uses: actions/upload-artifact@v2
      with:
        name: zbar
        path: ${{ github.workspace }}/zbar/*.zip
    - name: Upload release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ${{ github.workspace }}/zbar/*.zip